using System;

[module: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE0055:FixFormatting", Justification = "Autogenerated code in this project")]

namespace Database.Migrations
{
    /// <summary>
    /// EntityFramework migration stub.
    /// </summary>
    public static class Program
    {
        /// <summary>
        /// EntityFramework migration stub.
        /// </summary>
        public static void Main()
        {
            Console.WriteLine("This stub is only needed to make EF Core Migrations happy...");
        }
    }
}
